export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR";
export const ADD_CATEGORY_LOADING = "ADD_CATEGORY_LOADING";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";

export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";
export const DELETE_CATEGORY_LOADING = "DELETE_CATEGORY_LOADING";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";

export const EDIT_CATEGORY_ERROR = "EDIT_CATEGORY_ERROR";
export const EDIT_CATEGORY_LOADING = "EDIT_CATEGORY_LOADING";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";

export const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR";
export const FETCH_CATEGORIES_LOADING = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

export const TOGGLE_UPDATE = "TOGGLE_UPDATE";
export const TOGGLE_DELETE = "TOGGLE_DELETE";
